---
title: "HW 10: Data Visualization 1"
author: "William Zoughaib"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

#### Install and load (library) tidyverse,here,GGally,patchwork
```{r}
library(tidyverse)
library(here)
library(GGally)
library(patchwork)
```
***
#### Load sparrows.txt.  Wrangle Data
```{r}
sparrows_raw <- read_tsv(here("data","sparrows.txt"))
sparrows_raw
```
```{r}
sparrows <- sparrows_raw %>% 
  mutate(box_group = "Sparrows",
         row_order = 1:nrow(.))
view(sparrows)
```
```{r}
sparrows
# via mutate, we added box_group and row_order columns
```
***
#### Figure 2 Outliers Plots
```{r}
plot_box <- sparrows %>% 
  ggplot(aes(x=box_group,y=wingcrd))+
  geom_boxplot(width=0.25)+
  labs(x=NULL,y="Wing length (mm)")
```
```{r}
plot_cleveland <- sparrows %>% 
  ggplot(aes(x=wingcrd,y=row_order))+
  geom_point()+
  labs(x="Wing length (mm)",
       y="Order of the data")
```
#### add plot_box and plot_cleveland together.  coord_flip()
```{r}
plot_box+plot_cleveland+coord_flip()
```
***
#### Figure 3: Outliers
```{r}
p_culmen <- sparrows %>% 
  ggplot(aes(y=row_order))+
  geom_point(aes(x=culmen))+
  theme(axis.title.y=element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y=element_blank())
p_nalospi <- sparrows %>% 
  ggplot(aes(y=row_order))+
  geom_point(aes(x=nalospi))+
  theme(axis.title.y=element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y=element_blank())
p_wt <- sparrows %>% 
  ggplot(aes(y=row_order))+
  geom_point(aes(x=wt))+
  theme(axis.title.y=element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y=element_blank())
p_wingcrd <- sparrows %>% 
  ggplot(aes(y=row_order))+
  geom_point(aes(x=wingcrd))+
  theme(axis.title.y=element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y=element_blank())
p_tarsus <- sparrows %>% 
  ggplot(aes(y=row_order))+
  geom_point(aes(x=tarsus))+
  theme(axis.title.y=element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y=element_blank())
p_head <- sparrows %>% 
  ggplot(aes(y=row_order))+
  geom_point(aes(x=head))+
  theme(axis.title.y=element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y=element_blank())
p_culmen+p_nalospi+p_wt+p_wingcrd+p_tarsus+p_head +plot_layout(ncol=3,nrow=2)

# nalospi,tarsus,and head have outlier data
```
***
#### Figure 5: distribution
#### Histogram
```{r}
h1 <- sparrows %>% 
  filter(Month %in% 6:8) %>% 
  ggplot()+
  geom_histogram(aes(x=wt),
                 binwidth = 0.5,
                 boundary=0,
                 closed="right",
                 color="black")+
  scale_x_continuous(breaks=seq(14,28,by=2))
h1
# I have filtered months 6:8 and created a histogram.  binwidth=0.5 so it looks like two bars per complete 1 integer.  So 18-18.5 & 18.51-19
```
#### Faceted Histogram
```{r}
h2 <- sparrows %>% 
  filter(Month%in%6:8) %>% 
  mutate(Month=case_when(
    Month==6~"June",
    Month==7~"July",
    Month==8~"August")) %>% 
  ggplot()+
  geom_histogram(aes(x=wt),
                 binwidth=0.5,
                 boundary=0,
                 color="black")+
  scale_x_continuous(breaks = seq(14,28,by=2))+
  facet_wrap(~Month,ncol=1)
```
#### Assemble both histograms
```{r}
h1+h2
# This looks ok, I would honestly prefer the larger graphs shown in the homework sheet.  The right panel histograms are kind of small and hard to interpret...
```
***
#### Figure 10: Relationships

