---
title: "HW 14: Maps"
author: "William Zoughaib"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r}
library(here)
library(raster)
library(sf)
library(tidyverse)
library(ggthemes)
library(patchwork)
library(maptools)
library(ggmap)
library(marmap)
```
***
### Part 1: Outline maps
***
#### U.S. map
```{r}
# Outline of the 48 contiguous states
usa <-map_data(map="state")
str(usa)
# Outline of just Missouri
us_missouri <- map_data(map="state",region="missouri")
# Outline of Alabama, Florida, Mississippi,and North Carolina
us_other <- subset(x=usa,subset=region%in%c("alabama","florida","mississippi","north carolina"))
# Case matters with region =
```
#### Use us_other to lay first map layer
```{r}
ggplot()+
  geom_polygon(data=us_other,aes(x=long,y=lat,group=group),fill="gray")
# Interesting...
```
#### Now add Missouri to previous plot (us_missouri)
```{r}
ggplot()+
  geom_polygon(data=us_other,aes(x=long,y=lat,group=group),fill="gray")+
  geom_polygon(data=us_missouri,aes(x=long,y=lat,group=group),color="black")
# Plot appears stretched...but otherwise its ok.  Probably has to do with view.  
```
#### Add the 48 states plot to the previous two layers (usa)
```{r}
ggplot()+
  geom_polygon(data=us_other,aes(x=long,y=lat,group=group),fill="gray")+
  geom_polygon(data=us_missouri,aes(x=long,y=lat,group=group),color="black")+
  geom_polygon(data=usa,aes(x=long,y=lat,group=group),fill=NA,color="black")
# Way cool, much wow
```
#### save plot to us_map, add theme_map(),use coord_fixed of 1.3
```{r}
us_map <- ggplot()+
  geom_polygon(data=us_other,aes(x=long,y=lat,group=group),fill="gray")+
  geom_polygon(data=us_missouri,aes(x=long,y=lat,group=group),color="black")+
  geom_polygon(data=usa,aes(x=long,y=lat,group=group),fill=NA,color="black")+
  theme_map()+
  coord_fixed(1.3)
us_map
# removed grid background theme.  I like color though.  Hope we learn color.  
```
***
#### Missouri map: Highlight Scott County
```{r}
missouri <- map_data("county","missouri")
mo_scott <- subset(missouri,subregion%in%c("scott"))
# Saved missouri variable and then added it to the subset mo_scott variable
mo_map <- ggplot()+
  geom_polygon(data=missouri,aes(x=long,y=lat,group=group),fill=NA,color="black")+
  geom_polygon(data=mo_scott,aes(x=long,y=lat,group=group),fill="black")+
  theme_map()+
  coord_fixed(1.3)
mo_map
# Where da color at.  
```
***
#### Patchwork for us_map and mo_map
```{r}
us_map+mo_map+plot_layout(nrow=1,widths=c(1.5,1))
# I like it.  Much easier than yesterday
```

